name: PEDIY-CheckIn
on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths-ignore: 
      - 'README.md'
      - 'imgs/**'
  schedule:
    - cron: '30 22 * * *'  # 添加引号符合最新规范

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: write  # 为删除工作流运行添加必要权限
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # 升级到最新稳定版
        
      - name: Setup Node.js
        uses: actions/setup-node@v4  # 升级到最新版
        with:
          node-version: '20'  # 更新到当前LTS版本
          cache: 'npm'  # 添加npm缓存提高性能
          
      - name: Install dependencies
        run: npm ci  # 使用ci而不是install，确保依赖一致性
        
      - name: Run CheckIn
        run: node main.js
        env:
          PUSHPLUS: ${{ secrets.PUSHPLUS }}
          COOKIE: ${{ secrets.COOKIE }}
          
      - name: Keep workflow alive
        if: always()  # 确保即使主步骤失败也执行
        uses: gautamkrishnar/keepalive-workflow@v1  # 使用固定版本而非master
        
      - name: Clean up workflow runs
        if: always()  # 确保清理步骤总是执行
        uses: actions/delete-workflow-runs@v1  # GitHub官方维护的替代方案
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 9
