name: PEDIY-CheckIn
on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths-ignore: 
      - 'README.md'
      - 'imgs/**'
  schedule:
    - cron: '30 22 * * *'  # 签到时间
    - cron: '0 */6 * * *'   # 保持活跃(每6小时)

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run CheckIn
        if: github.event_name == 'schedule' && github.event.schedule == '30 22 * * *'
        run: node main.js
        env:
          PUSHPLUS: ${{ secrets.PUSHPLUS }}
          COOKIE: ${{ secrets.COOKIE }}
          
      - name: Clean up workflow runs
        if: always()
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 9
